### ISSUE TITLE
Nav Menu isn't working

### ISSUE THREAD

**Issue by mswezey23** [ShiftNrg/shift-website#17]
When a user clicks on the nav and selects an item; it should bring the user to that section of the page and close out the nav. 

It does bring the user to the section. But it does not auto-close the nav.

![image](https://user-images.githubusercontent.com/1747669/107907969-98e66180-6f1a-11eb-9a59-879e6a90e9da.png)

**Comment by Alexa101101** [comment]
this issue self-resolved, except when clicking the nano wallet which opens the GH link and leaves the nav bar open
